alias vimrc="cd ~/.config/nvim;chezmoi edit init.lua"
alias zshrc="cd ~/;chezmoi .zshrc"
alias aliasrc="chezmoi edit ~/.config/aliases/aliases.zsh"
alias myip="curl http://ipecho.net/plain; echo"
alias install="cd ~/bin;nvim ~/bin/skogix.pkgs;sh /home/skogix/bin/archlinux.sh --skogix;chezmoi re-add;chezmoi apply"
alias lazychezmoi="chezmoi cd;lazygit"
alias edit="chezmoi edit; chezmoi apply"
# test
alias ljud="systemctl --user restart wireplumber pipewire pipewire-pulse"
alias dockerpurge="docker system prune -a --volumes"
alias dlog="docker compose -f /home/skogix/srv/docker-compose.yaml logs"
alias dtail="docker compose -f /home/skogix/srv/docker-compose.yaml logs -tf --tail="50" crowdsec"
alias dup="docker compose -f /home/skogix/srv/docker-compose.yaml up -d"
alias dprune="docker system prune -a --volumes"
alias dtop="oxker"
